# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Another blog
tagline:          'A blog'
description:      'A blog for when I am bored.'
url:              https://aulisius.github.io
baseurl:          https://aulisius.github.io/

author:
  name:           'Faizaan'
  url:            https://github.com/aulisius

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aulisius/aulisius.github.io
